### ISSUE TITLE
Pre-trained Models

### ISSUE THREAD

**Issue by DucHuyDS** [caodoanh2001/upar_challenge#3]
Hello, could you provide the pretrained model '/pretrained/swin_base_patch4_window7_224_22k.pth' and where did you get it from? Because the models I've obtained are hardly compatible with your architecture. Also, I followed each step in the code you mentioned, but when training the model with the PA100k and PETA datasets, it doesn't achieve results close to what you mentioned in the paper. Could you provide me with the pretrained models for PETA and PA100k that you trained previously? I'm conducting some research on this problem. Thank you for your contribution.

**Comment by caodoanh2001** [comment]
Hi mate,

Please check this checkpoint for PETA dataset: https://drive.google.com/file/d/1CfzpDAuf3Q8lEm-Rm7pgS6FrkW8LJ00U/view?usp=drive_link

Let me know if there are any issues that occur.
